[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
shared = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "process", "io-util", "time", "sync"] }
tonic = { workspace = true }
tonic-health = { workspace = true }

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
]
[dev-dependencies]
serde_json = { workspace = true }
