[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4.39"
shared = { path = "../shared" }
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros", "process", "io-util", "time", "sync"] }
tonic = "0.12.3"
tonic-health = "0.12.3"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
]