//! Static checks on the installer's configuration files.
//!
//! These are regression guards, not behavioral tests: they read the files
//! the installer ships and assert the properties that broke when the
//! install location moved to `C:\Program Files\Azookey` (a path with a
//! space) and to a machine-wide scope. Actual install/uninstall behavior
//! still needs a VM pass.
//!
//! They live in the launcher crate because the launcher is what the
//! startup task ultimately starts; there is no installer crate.

use std::path::PathBuf;

fn installer_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../installer")
}

fn read(name: &str) -> String {
    let path = installer_dir().join(name);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
}

/// The task's Arguments become `C:\Program Files\Azookey\launch.vbs` at
/// install time. wscript.exe does not do CreateProcess-style prefix
/// guessing: an unquoted path with a space makes it look for
/// `C:\Program`, and logon autostart silently dies.
#[test]
fn task_xml_quotes_the_script_path() {
    let xml = read("Azookey Startup.xml");

    assert!(
        xml.contains(r#"<Arguments>"PATH_TO_VBS"</Arguments>"#),
        "the wscript argument must be quoted, or a space in the install \
         path breaks logon autostart"
    );
}

/// The install is machine-wide (Program Files, HKLM/HKCR registrations),
/// so the logon trigger must fire for every user. A principal of
/// BUILTIN\Administrators (S-1-5-32-544) means standard users get no
/// launcher, no server, no UI — a completely dead IME.
#[test]
fn task_xml_triggers_for_all_users() {
    let xml = read("Azookey Startup.xml");

    assert!(
        !xml.contains("S-1-5-32-544"),
        "the startup task must not be restricted to Administrators"
    );
    assert!(
        xml.contains("S-1-5-32-545") || xml.contains("S-1-5-4"),
        "the startup task should trigger for Users (S-1-5-32-545) or \
         INTERACTIVE (S-1-5-4)"
    );
}

/// The file is written and round-tripped (LoadStringFromFile /
/// SaveStringToFile as AnsiString) as 8-bit text, so the XML declaration
/// must not claim UTF-16 — MSXML may refuse the mismatch outright.
#[test]
fn task_xml_encoding_declaration_matches_the_bytes() {
    let path = installer_dir().join("Azookey Startup.xml");
    let bytes = std::fs::read(&path).unwrap();

    assert!(
        bytes.starts_with(b"<?xml"),
        "the task XML is expected to be 8-bit text without a BOM \
         (the installer round-trips it as AnsiString)"
    );

    let xml = String::from_utf8(bytes).expect("task XML should be valid UTF-8");
    assert!(
        !xml.contains(r#"encoding="UTF-16""#),
        "the declaration claims UTF-16 but the bytes are 8-bit; \
         declare UTF-8 instead"
    );
}

/// launch.vbs is generated by [Code] in Installer.iss. The path handed to
/// WScript.Shell.Run must be quoted inside the VBScript string (doubled
/// quotes), or CreateProcess prefix-guessing lets a planted
/// `C:\Program.exe` run instead — elevated, since the task runs with
/// RunLevel=HighestAvailable.
#[test]
fn launch_vbs_generation_quotes_the_exe_path() {
    let iss = read("Installer.iss");

    let run_line = iss
        .lines()
        .find(|l| l.contains("objShell.Run"))
        .expect("Installer.iss should generate an objShell.Run line");

    assert!(
        run_line.contains(r#"objShell.Run """#) && run_line.contains(r#"""","#),
        "the launcher path must be wrapped in doubled VBScript quotes: \
         got {run_line}"
    );
}

/// Uninstall must stop the running IME processes, or their exe/dll files
/// stay locked and {app} can't be removed.
#[test]
fn uninstall_stops_the_running_processes() {
    let iss = read("Installer.iss");

    assert!(
        iss.contains(r#"Filename: "taskkill""#),
        "uninstall should invoke taskkill"
    );

    // Inno line-continues each field, so the process list is on the
    // Parameters line, separate from the Filename line
    let params = iss
        .lines()
        .find(|l| l.contains("/IM") && l.contains("launcher.exe"))
        .expect("Installer.iss should pass the processes to taskkill via /IM");

    for proc in ["launcher.exe", "ui.exe", "azookey-server.exe"] {
        assert!(
            params.contains(proc),
            "uninstall's taskkill must target {proc}: got {params}"
        );
    }
}

/// The build-directory glob must not re-copy the TIP DLL: it is already
/// placed and registered as azookey.dll / azookey32.dll, so the glob would
/// only add unregistered dead copies.
#[test]
fn build_glob_excludes_the_registered_dll() {
    let iss = read("Installer.iss");

    let glob_line = iss
        .lines()
        .find(|l| l.contains(r#"Source: "../build/*""#))
        .expect("Installer.iss should have a build/* glob");

    assert!(
        glob_line.contains("azookey_windows.dll"),
        "the build/* glob must exclude azookey_windows.dll: got {glob_line}"
    );
}
