//! Static checks on the installer's configuration files.
//!
//! These are regression guards, not behavioral tests: they read the files
//! the installer ships and assert the properties that broke when the
//! install location moved to `C:\Program Files\Azookey` (a path with a
//! space) and to a machine-wide scope. Actual install/uninstall behavior
//! still needs a VM pass.
//!
//! They live in the launcher crate because the launcher is what the
//! startup task ultimately starts; there is no installer crate.

use std::path::PathBuf;

fn installer_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../installer")
}

fn read(name: &str) -> String {
    let path = installer_dir().join(name);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
}

/// The task's Arguments become `C:\Program Files\Azookey\launch.vbs` at
/// install time. wscript.exe does not do CreateProcess-style prefix
/// guessing: an unquoted path with a space makes it look for
/// `C:\Program`, and logon autostart silently dies.
#[test]
fn task_xml_quotes_the_script_path() {
    let xml = read("Azookey Startup.xml");

    assert!(
        xml.contains(r#"<Arguments>"PATH_TO_VBS"</Arguments>"#),
        "the wscript argument must be quoted, or a space in the install \
         path breaks logon autostart"
    );
}

/// The install is machine-wide (Program Files, HKLM/HKCR registrations),
/// so the logon trigger must fire for every user. A principal of
/// BUILTIN\Administrators (S-1-5-32-544) means standard users get no
/// launcher, no server, no UI — a completely dead IME.
#[test]
fn task_xml_triggers_for_all_users() {
    let xml = read("Azookey Startup.xml");

    assert!(
        !xml.contains("S-1-5-32-544"),
        "the startup task must not be restricted to Administrators"
    );
    assert!(
        xml.contains("S-1-5-32-545") || xml.contains("S-1-5-4"),
        "the startup task should trigger for Users (S-1-5-32-545) or \
         INTERACTIVE (S-1-5-4)"
    );
}

/// The launcher supervises the whole IME stack, so the startup task must
/// keep running on battery power: with StopIfGoingOnBatteries=true, Task
/// Scheduler kills the launcher (and with it server + UI, via the job
/// object) the moment a laptop is unplugged, leaving the user without an
/// IME until the next logon.
#[test]
fn task_xml_survives_switching_to_battery_power() {
    let xml = read("Azookey Startup.xml");

    assert!(
        xml.contains("<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>"),
        "the startup task must not stop when the machine goes on battery"
    );
    assert!(
        xml.contains("<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>"),
        "the startup task must start even when the machine is on battery"
    );
}

/// The file is written and round-tripped (LoadStringFromFile /
/// SaveStringToFile as AnsiString) as 8-bit text, so the XML declaration
/// must not claim UTF-16 — MSXML may refuse the mismatch outright.
#[test]
fn task_xml_encoding_declaration_matches_the_bytes() {
    let path = installer_dir().join("Azookey Startup.xml");
    let bytes = std::fs::read(&path).unwrap();

    assert!(
        bytes.starts_with(b"<?xml"),
        "the task XML is expected to be 8-bit text without a BOM \
         (the installer round-trips it as AnsiString)"
    );

    let xml = String::from_utf8(bytes).expect("task XML should be valid UTF-8");
    assert!(
        !xml.contains(r#"encoding="UTF-16""#),
        "the declaration claims UTF-16 but the bytes are 8-bit; \
         declare UTF-8 instead"
    );
}

/// launch.vbs is generated by [Code] in Installer.iss. The path handed to
/// WScript.Shell.Run must be quoted inside the VBScript string (doubled
/// quotes), or CreateProcess prefix-guessing lets a planted
/// `C:\Program.exe` run instead — elevated, since the task runs with
/// RunLevel=HighestAvailable.
#[test]
fn launch_vbs_generation_quotes_the_exe_path() {
    let iss = read("Installer.iss");

    let run_line = iss
        .lines()
        .find(|l| l.contains("objShell.Run"))
        .expect("Installer.iss should generate an objShell.Run line");

    assert!(
        run_line.contains(r#"objShell.Run """#) && run_line.contains(r#"""","#),
        "the launcher path must be wrapped in doubled VBScript quotes: \
         got {run_line}"
    );
}

/// Uninstall must stop the running IME processes, or their exe/dll files
/// stay locked and {app} can't be removed.
#[test]
fn uninstall_stops_the_running_processes() {
    let iss = read("Installer.iss");

    assert!(
        iss.contains(r#"Filename: "taskkill""#),
        "uninstall should invoke taskkill"
    );

    // Inno line-continues each field, so the process list is on the
    // Parameters line, separate from the Filename line
    let params = iss
        .lines()
        .find(|l| l.contains("/IM") && l.contains("launcher.exe"))
        .expect("Installer.iss should pass the processes to taskkill via /IM");

    for proc in ["launcher.exe", "ui.exe", "azookey-server.exe"] {
        assert!(
            params.contains(proc),
            "uninstall's taskkill must target {proc}: got {params}"
        );
    }
}

/// Returns the body of a `[Code]` procedure/function, from its header to
/// the next top-level declaration.
fn code_block(iss: &str, header: &str) -> String {
    let start = iss
        .find(header)
        .unwrap_or_else(|| panic!("Installer.iss should define {header}"));
    let rest = &iss[start..];
    let end = rest[1..]
        .find("\nprocedure ")
        .into_iter()
        .chain(rest[1..].find("\nfunction "))
        .min()
        .map(|i| i + 1)
        .unwrap_or(rest.len());
    rest[..end].to_string()
}

/// Issue #4: an upgrade installs over a running stack, whose executables
/// are locked, so installation must stop it before the [Files] copies —
/// not only on uninstall.
#[test]
fn install_stops_the_running_stack_before_copying() {
    let iss = read("Installer.iss");

    assert!(
        iss.contains("function PrepareToInstall("),
        "the stack must be stopped from PrepareToInstall, which also runs \
         for a silent install (a wizard-page hook would not)"
    );

    let body = code_block(&iss, "procedure StopRunningStack");
    for proc in [
        "launcher.exe",
        "ui.exe",
        "azookey-server.exe",
        "Azookey.exe",
    ] {
        assert!(
            body.contains(proc),
            "install-time taskkill must target {proc}: got {body}"
        );
    }
    assert!(
        body.contains("/End /TN \"Azookey Startup\""),
        "the startup task must be ended, or it can relaunch the stack \
         between the kill and the copies"
    );
}

/// launcher.exe runs as administrator, and the startup task is
/// machine-scope. `runascurrentuser` de-elevates the spawned process, so a
/// taskkill carrying it silently fails to kill the launcher and the task
/// deletion is denied — the exact lock the kill exists to prevent.
#[test]
fn process_teardown_is_not_de_elevated() {
    let iss = read("Installer.iss");

    let start = iss
        .find("[UninstallRun]")
        .expect("Installer.iss should have an [UninstallRun] section");
    let rest = &iss[start..];
    let end = rest[1..].find("\n[").map(|i| i + 1).unwrap_or(rest.len());
    // directives only: an Inno comment line starts with ';', and the comment
    // above these entries names the flag in order to explain its absence
    let directives: String = rest[..end]
        .lines()
        .filter(|l| !l.trim_start().starts_with(';'))
        .collect::<Vec<_>>()
        .join("\n");

    assert!(
        !directives.contains("runascurrentuser"),
        "uninstall's taskkill/schtasks must stay elevated: got {directives}"
    );
}

/// The build-directory glob must not re-copy the TIP DLL: it is already
/// placed and registered as azookey.dll / azookey32.dll, so the glob would
/// only add unregistered dead copies.
#[test]
fn build_glob_excludes_the_registered_dll() {
    let iss = read("Installer.iss");

    let glob_line = iss
        .lines()
        .find(|l| l.contains(r#"Source: "../build/*""#))
        .expect("Installer.iss should have a build/* glob");

    assert!(
        glob_line.contains("azookey_windows.dll"),
        "the build/* glob must exclude azookey_windows.dll: got {glob_line}"
    );
}

/// B22: the Tauri settings app runs its NSIS from Inno's elevated context.
/// Without perMachine it defaults to currentUser and lands in the elevating
/// ADMIN's %LOCALAPPDATA%/HKCU — the logon user can't launch it, the exact
/// bug the machine-wide move (297a054) fixed everywhere else.
#[test]
fn tauri_settings_app_installs_per_machine() {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../frontend/src-tauri/tauri.conf.json");
    let conf = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let json: serde_json::Value = serde_json::from_str(&conf).expect("tauri.conf.json is JSON");

    assert_eq!(
        json.pointer("/bundle/windows/nsis/installMode")
            .and_then(|v| v.as_str()),
        Some("perMachine"),
        "the settings app must install perMachine, or it lands in the \
         elevating admin's profile"
    );
}

/// B22: the Inno uninstaller chains into the settings app's NSIS
/// uninstaller. With perMachine its uninstall key is in HKLM (HKCU only as
/// a legacy fallback), the stored quoted path must be unquoted for
/// ShellExec's Filename, and NSIS is only silent with /S.
#[test]
fn uninstall_chains_the_settings_app_from_hklm_silently() {
    let iss = read("Installer.iss");
    let start = iss
        .find("procedure UninstallAzookey")
        .expect("Installer.iss should define UninstallAzookey");
    let rest = &iss[start..];
    let end = rest[1..]
        .find("\nprocedure ")
        .map(|i| i + 1)
        .unwrap_or(rest.len());
    let proc_body = &rest[..end];

    assert!(
        proc_body.contains("RegQueryStringValue(HKLM,"),
        "UninstallAzookey must read the perMachine (HKLM) uninstall key"
    );
    assert!(
        proc_body.contains("RemoveQuotes(UninstallString)"),
        "the quoted UninstallString must be unquoted for ShellExec's Filename"
    );
    assert!(
        proc_body.contains("'/S'"),
        "the NSIS uninstaller must be passed /S to actually run silently"
    );
}

/// The product version is single-sourced from [workspace.package] in the
/// root Cargo.toml. The installer must take its versions from the
/// generated Version.iss (written by the build_installer task), and the
/// Tauri config must not pin its own copy — omitting "version" makes
/// Tauri fall back to src-tauri's (workspace-inherited) Cargo version.
#[test]
fn product_version_is_single_sourced() {
    let iss = read("Installer.iss");
    assert!(
        iss.contains("#include \"Version.iss\""),
        "Installer.iss must include the generated Version.iss"
    );
    assert!(
        !iss.contains("#define MyAppVersion \""),
        "MyAppVersion must not be hardcoded in Installer.iss"
    );
    assert!(
        !iss.contains("#define TauriAppVersion \""),
        "TauriAppVersion must not be hardcoded in Installer.iss"
    );

    let tauri_conf_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../frontend/src-tauri/tauri.conf.json");
    let tauri_conf = std::fs::read_to_string(&tauri_conf_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", tauri_conf_path.display()));
    assert!(
        !tauri_conf.contains("\"version\""),
        "tauri.conf.json must not pin its own version; it inherits the \
         workspace version through src-tauri/Cargo.toml"
    );
}
