[package]
name = "shared"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["net", "time"] }
tower = "0.5.1"
hyper-util = { version = "0.1.9", features = ["tokio"] }

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
]

[build-dependencies]
tonic-build = { workspace = true }
