; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "CodeDependencies.iss"

#define MyAppName "Azookey"
; Version.iss is generated by `cargo make build` (build_installer) from the
; [workspace.package] version in the root Cargo.toml — the single source of
; the product version. It defines MyAppVersion and TauriAppVersion (equal:
; tauri.conf.json omits "version", so the Tauri app inherits the same
; workspace version and its NSIS filename below is derived from it).
; If iscc says the file is missing, run `cargo make build` instead of
; invoking iscc directly.
#include "Version.iss"
#define TauriSetupExe "Azookey_" + TauriAppVersion + "_x64-setup.exe"
#define MyAppPublisher "fkunn1326"
#define MyAppURL "https://github.com/fkunn1326/azooKey-Windows/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{80B746D4-D74D-4345-8F81-47E06BCAB515}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Machine-wide install: this is an admin install (PrivilegesRequired=admin)
; that registers the IME machine-wide (HKCR/TSF, HKLM WER). {userappdata}
; would resolve to the ELEVATING admin's roaming profile — often a different
; account than the logged-in user — so the registered DLL paths could point
; into the wrong profile and other users would never find the files.
; {autopf} = Program Files (64-bit here), readable by every user. Mutable
; runtime data (settings.json, logs, dumps) lives in each user's
; %APPDATA%/%LOCALAPPDATA% via the app itself, not here.
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=../build
OutputBaseFilename=azookey-setup
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Files]
Source: "../build/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey.dll"; Flags: ignoreversion regserver 64bit
Source: "../build/x86/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey32.dll"; Flags: ignoreversion regserver 32bit
; exclude the installer's own output (OutputDir is also ../build): a stale
; azookey-setup.exe would otherwise be bundled into — or clash with — the new one.
; also exclude azookey_windows*.dll: the TIP is already placed and registered
; above as azookey.dll / azookey32.dll, so the glob would only add unregistered
; dead copies. The wildcard matters as much as the bare name: a working tree
; accumulates versioned deploy copies (azookey_windows_batch10.dll and
; friends, one per regsvr32 target), and shipping those is ~100 MB of dead
; weight plus a stale DLL sitting next to the live one for a future regsvr32
; to pick by mistake. CI builds from a clean checkout and never had them.
; *.bak is the same story in a different shape: hand-made backups of a
; binary before swapping it (ui.exe.pre-aria.bak and the like) are working-
; tree leftovers, never runtime assets.
; ui.exe.WebView2 is runtime state: the WebView2 profile ui.exe used to
; create next to itself when the stack was run from build/. Since issue #54
; the profile lives under %LOCALAPPDATA% and is no longer created here, but
; a working tree that predates that still has one — same leftover class as
; the entries above, so the exclusion stays.
Source: "../build/*"; Excludes: "azookey-setup.exe,azookey_windows*.dll,*.bak,\ui.exe.WebView2\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "../target/release/bundle/nsis/{#TauriSetupExe}"; Flags: dontcopy noencryption
Source: "./Azookey Startup.xml"; Flags: dontcopy noencryption
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Windows Error Reporting LocalDumps: capture minidumps of native crashes
; (e.g. inside the Swift runtime or llama.cpp) for field diagnosis.
; DumpFolder is REG_EXPAND_SZ, so each user's dumps land in their own
; %LOCALAPPDATA%\Azookey\dumps. DumpType=1 = minidump, capped at 5 files.
; Only azookey-server.exe: LocalDumps keys match by exe NAME alone, so a
; generic name like ui.exe would also capture unrelated applications.
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: expandsz; ValueName: "DumpFolder"; ValueData: "%LOCALAPPDATA%\Azookey\dumps"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: dword; ValueName: "DumpType"; ValueData: "1"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: dword; ValueName: "DumpCount"; ValueData: "5"

[Run]
Filename: "icacls"; \
  Parameters: "{app}\azookey.dll /grant ""*S-1-15-2-1:(RX)"""; \
  Description: "Grant Permission"; \
  Flags: runhidden postinstall runascurrentuser
Filename: "icacls"; \
  Parameters: "{app}\azookey32.dll /grant ""*S-1-15-2-1:(RX)"""; \
  Description: "Grant Permission"; \
  Flags: runhidden postinstall runascurrentuser

[UninstallDelete]
; launch.vbs is created at post-install by [Code], so Setup does not track
; it; delete it explicitly, otherwise it keeps {app} from being removed
Type: files; Name: "{app}\launch.vbs"
; ui.exe.WebView2 is the same story: builds before the %LOCALAPPDATA% move
; (issue #54) let WebView2 create its profile next to the exe, and a folder
; Setup never installed is a folder Setup never removes.
Type: filesandordirs; Name: "{app}\ui.exe.WebView2"

[UninstallRun]
; stop the running IME processes first, or their exe/dll files stay locked
; and {app} can't be removed (UninstallNeedRestart hides this by deferring
; deletion to the reboot, but the unregistered DLL keeps loading until then).
; Azookey.exe is the settings app, whose NSIS uninstaller is chained from
; usPostUninstall and cannot delete its own running exe either.
; NOT runascurrentuser: that de-elevates the child, and launcher.exe runs as
; administrator — a de-elevated taskkill cannot touch it, and only an
; elevated schtasks may delete a machine-scope task.
Filename: "taskkill"; \
  RunOnceId: "KillAzookeyProcs"; \
  Parameters: "/F /IM launcher.exe /IM ui.exe /IM azookey-server.exe /IM Azookey.exe"; \
  Flags: runhidden
Filename: "schtasks"; \
  RunOnceId: "DelAzookeyStartupTask"; \
  Parameters: "/Delete /TN ""Azookey Startup"" /F"; \
  Flags: runhidden

[Code]
function InitializeSetup: Boolean;
begin
  ExtractTemporaryFile('{#TauriSetupExe}');
  Dependency_AddVC2015To2022x64;
  Dependency_AddVC2015To2022x86;
  Dependency_Add('{#TauriSetupExe}',
    '/q',
    'Azookey',
    '', '', True, False);

  Result := True;
end;

function UninstallNeedRestart(): Boolean;
begin
  Result := True;
end;

function CmdLineContains(Param: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
  begin
    if CompareText(ParamStr(I), Param) = 0 then
    begin
      Result := True;
      Exit;
    end;
  end;
end;
procedure UpdateTaskXml();
var
  TaskXmlPath: string;
  TaskXmlContentAnsi: AnsiString;
  TaskXmlContent: String;
  Dummy: Integer;
begin
  ExtractTemporaryFile('Azookey Startup.xml'); // ファイル展開
  TaskXmlPath := ExpandConstant('{tmp}\Azookey Startup.xml');

  LoadStringFromFile(TaskXmlPath, TaskXmlContentAnsi)

  TaskXmlContent := String(TaskXmlContentAnsi);

  StringChange(TaskXmlContent, 'PATH_TO_VBS', ExpandConstant('{app}\launch.vbs'));
  TaskXmlContentAnsi := AnsiString(TaskXmlContent);
  SaveStringToFile(TaskXmlPath, TaskXmlContentAnsi, False);

  ShellExec('', 'schtasks', '/Create /F /TN "Azookey Startup" /XML "' + TaskXmlPath + '"', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
  ShellExec('', 'schtasks', '/Run /TN "Azookey Startup"', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
end;

procedure CreateVbsFile();
var
  VbsFile: string;
  VbsContent: AnsiString;
begin
  VbsFile := ExpandConstant('{app}\launch.vbs');
  VbsContent :=
    'Set objShell = CreateObject("WScript.Shell")' + #13#10 +
    // the path must be quoted inside the VBScript string (doubled quotes):
    // {app} contains a space, and an unquoted Run argument lets a planted
    // C:\Program.exe start instead — elevated, via the scheduled task
    'objShell.Run """' + ExpandConstant('{app}\launcher.exe') + '""", 0, False' + #13#10;

  if SaveStringToFile(VbsFile, VbsContent, False) then
  begin
    Log('VBS file created: ' + VbsFile);
  end
  else
  begin
    Log('Failed to create VBS file: ' + VbsFile);
  end;
end;

procedure UninstallAzookey();
var
  UninstallString: string;
  Dummy: Integer;
begin
  { The settings app installs perMachine (tauri.conf.json installMode), so
    its NSIS uninstall key lives in HKLM. HKCU remains as a fallback for
    installs made before the perMachine switch (those landed in the
    elevating admin's HKCU). The stored UninstallString is quoted, which
    ShellExec's Filename does not accept (RemoveQuotes), and NSIS only runs
    silently with /S - SW_HIDE alone still showed its window. }
  if not RegQueryStringValue(HKLM, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\Azookey', 'UninstallString', UninstallString) then
    RegQueryStringValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\Azookey', 'UninstallString', UninstallString);
  if UninstallString <> '' then
  begin
    ShellExec('', RemoveQuotes(UninstallString), '/S', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
  end;
end;


// An upgrade installs over a running stack: launcher.exe, ui.exe and
// azookey-server.exe hold the installed executables open, so the [Files]
// copies land on in-use files and turn into a Restart Manager prompt, a
// forced app close, or an outright failure. The uninstaller already stops
// these processes; installation has to do the same first.
//
// Deliberately elevated — no runascurrentuser / ShellExecAsOriginalUser:
// launcher.exe runs as administrator, so a de-elevated taskkill cannot
// touch it.
//
// Note this does not unload azookey.dll from the text applications that
// have it loaded; those are the host's processes, not ours, and Inno's
// Restart Manager handling already covers that case.
//
// Line comments, not brace comments: a { } comment mentioning an Inno
// constant would be closed early by the constant's own closing brace.
// Counts our runtime processes, optionally terminating each, and reports
// whether WMI itself could be reached (Failed) — "could not look" is not the
// same answer as "none running".
//
// Why WMI rather than taskkill: taskkill can only match an image NAME, and
// ui.exe and launcher.exe are generic enough to belong to something else
// entirely, so /IM reached every one of them on the machine. A process is
// ours when it runs from the install directory; azookey-server.exe and
// Azookey.exe are matched by name alone because those names are already
// unambiguous, and the settings app in particular lives wherever the chained
// Tauri NSIS put it rather than under {app}.
// WMI hands back NULL for fields we may not read (ExecutablePath on a
// process we cannot open), and Pascal Script has no VarToStr to absorb that.
function VariantText(const Value: Variant): String;
begin
  if VarIsNull(Value) or VarIsEmpty(Value) then
    Result := ''
  else
    Result := Value;
end;

function StackProcesses(const Dir: String; Kill: Boolean; var Failed: Boolean): Integer;
var
  Locator, Service, Items, Item: Variant;
  i: Integer;
  Prefix, Path, Name: String;
begin
  Result := 0;
  Failed := False;
  Prefix := Lowercase(AddBackslash(Dir));
  try
    Locator := CreateOleObject('WbemScripting.SWbemLocator');
    Service := Locator.ConnectServer('', 'root\CIMV2');
    Items := Service.ExecQuery('SELECT Name, ExecutablePath FROM Win32_Process' +
      ' WHERE Name = "launcher.exe" OR Name = "ui.exe"' +
      ' OR Name = "azookey-server.exe" OR Name = "Azookey.exe"');
    for i := 0 to Items.Count - 1 do
    begin
      Item := Items.ItemIndex(i);
      Name := Lowercase(VariantText(Item.Name));
      // ExecutablePath is NULL for processes we may not open; those are not
      // ours to kill anyway
      Path := Lowercase(VariantText(Item.ExecutablePath));
      if (Name = 'azookey-server.exe') or (Name = 'azookey.exe') or
         ((Path <> '') and (Pos(Prefix, Path) = 1)) then
      begin
        Result := Result + 1;
        if Kill then
        begin
          try
            Item.Terminate();
          except
            // already gone, or refused: the poll decides, not this call
          end;
        end;
      end;
    end;
  except
    Failed := True;
    Result := 0;
  end;
end;

procedure StopRunningStack();
var
  Dummy, Waited, Alive: Integer;
  Failed: Boolean;
begin
  // End the startup task first: it is what would put a fresh launcher back
  // between the kill and the copies.
  ShellExec('', 'schtasks', '/End /TN "Azookey Startup"', '', SW_HIDE, ewWaitUntilTerminated, Dummy);

  StackProcesses(ExpandConstant('{app}'), True, Failed);
  if Failed then
  begin
    // No WMI: fall back to the name-only kill. It is over-broad, but an
    // upgrade that cannot replace its locked files is the worse outcome.
    // Azookey.exe is the settings app, installed by the chained Tauri NSIS,
    // which cannot replace its own running exe either.
    Log('WMI unavailable; falling back to a name-only taskkill');
    ShellExec('', 'taskkill', '/F /IM launcher.exe /IM ui.exe /IM azookey-server.exe /IM Azookey.exe', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
    Sleep(1500);
    exit;
  end;

  // Termination is only REQUESTED above; the file handles close a moment
  // later. Poll for it instead of sleeping a fixed 1.5s, which proved
  // nothing on a slow machine and wasted the wait on a fast one.
  Waited := 0;
  repeat
    Alive := StackProcesses(ExpandConstant('{app}'), False, Failed);
    if (Alive = 0) or Failed then
      break;
    Sleep(250);
    Waited := Waited + 250;
  until Waited >= 15000;

  if Alive > 0 then
    Log('Timed out waiting for the running stack to exit; the file copies may hit locked files');
end;

// Runs just before the file copies, and unlike a wizard-page hook it also
// runs for a silent install.
function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  StopRunningStack();
  Result := '';
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    CreateVbsFile();
    UpdateTaskXml();
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpFinished then
    WizardForm.RunList.Visible := False;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    UninstallAzookey();
  end;
end;