; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "CodeDependencies.iss"

#define MyAppName "Azookey"
; Version.iss is generated by `cargo make build` (build_installer) from the
; [workspace.package] version in the root Cargo.toml — the single source of
; the product version. It defines MyAppVersion.
; If iscc says the file is missing, run `cargo make build` instead of
; invoking iscc directly.
#include "Version.iss"
#define MyAppPublisher "fkunn1326"
#define MyAppURL "https://github.com/fkunn1326/azooKey-Windows/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{80B746D4-D74D-4345-8F81-47E06BCAB515}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Machine-wide install: this is an admin install (PrivilegesRequired=admin)
; that registers the IME machine-wide (HKCR/TSF, HKLM WER). {userappdata}
; would resolve to the ELEVATING admin's roaming profile — often a different
; account than the logged-in user — so the registered DLL paths could point
; into the wrong profile and other users would never find the files.
; {autopf} = Program Files (64-bit here), readable by every user. Mutable
; runtime data (settings.json, logs, dumps) lives in each user's
; %APPDATA%/%LOCALAPPDATA% via the app itself, not here.
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=../build
OutputBaseFilename=azookey-setup
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
; The settings app is the only thing here with a face, so it is what the
; single Installed apps entry shows. Without this the entry gets Setup's
; generic icon — which is how it looked next to the Tauri NSIS entry that
; had a real one.
UninstallDisplayIcon={app}\Azookey.exe

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Files]
Source: "../build/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey.dll"; Flags: ignoreversion regserver 64bit
Source: "../build/x86/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey32.dll"; Flags: ignoreversion regserver 32bit
; exclude the installer's own output (OutputDir is also ../build): a stale
; azookey-setup.exe would otherwise be bundled into — or clash with — the new one.
; also exclude azookey_windows*.dll: the TIP is already placed and registered
; above as azookey.dll / azookey32.dll, so the glob would only add unregistered
; dead copies. The wildcard matters as much as the bare name: a working tree
; accumulates versioned deploy copies (azookey_windows_batch10.dll and
; friends, one per regsvr32 target), and shipping those is ~100 MB of dead
; weight plus a stale DLL sitting next to the live one for a future regsvr32
; to pick by mistake. CI builds from a clean checkout and never had them.
; *.bak is the same story in a different shape: hand-made backups of a
; binary before swapping it (ui.exe.pre-aria.bak and the like) are working-
; tree leftovers, never runtime assets.
; ui.exe.WebView2 is runtime state: the WebView2 profile ui.exe used to
; create next to itself when the stack was run from build/. Since issue #54
; the profile lives under %LOCALAPPDATA% and is no longer created here, but
; a working tree that predates that still has one — same leftover class as
; the entries above, so the exclusion stays.
Source: "../build/*"; Excludes: "azookey-setup.exe,azookey_windows*.dll,*.bak,\ui.exe.WebView2\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "./Azookey Startup.xml"; Flags: dontcopy noencryption
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
; The Tauri NSIS this replaces created a top-level, all-users
; $SMPROGRAMS\Azookey.lnk. {autoprograms} on an admin install is that same
; common Programs folder, so an upgrade overwrites the old shortcut in place
; — which IS the migration. From here on Inno owns it and removes it on
; uninstall, where the orphan used to be left behind.
;
; No desktop icon: the chained NSIS created one unconditionally when run
; silently, which is how it got onto machines nobody asked. RemoveLegacyNsisSettingsApp
; deletes that one and none is created in its place.
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\Azookey.exe"

[Registry]
; Windows Error Reporting LocalDumps: capture minidumps of native crashes
; (e.g. inside the Swift runtime or llama.cpp) for field diagnosis.
; DumpFolder is REG_EXPAND_SZ, so each user's dumps land in their own
; %LOCALAPPDATA%\Azookey\dumps. DumpType=1 = minidump, capped at 5 files.
; Only azookey-server.exe: LocalDumps keys match by exe NAME alone, so a
; generic name like ui.exe would also capture unrelated applications.
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: expandsz; ValueName: "DumpFolder"; ValueData: "%LOCALAPPDATA%\Azookey\dumps"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: dword; ValueName: "DumpType"; ValueData: "1"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: dword; ValueName: "DumpCount"; ValueData: "5"

[Run]
; Let AppContainer hosts (Start menu search, Store apps) read the TIP. Without
; this ACE they cannot load it, and the symptom is not an error: picking
; azooKey in such a host silently does nothing and the tray falls back to
; another IME.
;
; The path MUST be quoted. {app} defaults to "C:\Program Files\Azookey", and
; unquoted, icacls saw "C:\Program" and failed every install with exit code 87
; (ERROR_INVALID_PARAMETER). That went unnoticed because Program Files already
; hands this same right down by inheritance, so the default install looked
; right while the explicit grant had never once been applied - a directory the
; user picks that does not inherit it would have had no grant at all.
;
; Not postinstall: that turns the grant into a finish-page checkbox the user
; can clear, and it is not optional. Not runascurrentuser either: that
; de-elevates the child, and only Setup's own elevated token may rewrite an
; ACL under Program Files.
Filename: "icacls"; \
  Parameters: """{app}\azookey.dll"" /grant ""*S-1-15-2-1:(RX)"""; \
  StatusMsg: "Granting read access to sandboxed applications..."; \
  Flags: runhidden
Filename: "icacls"; \
  Parameters: """{app}\azookey32.dll"" /grant ""*S-1-15-2-1:(RX)"""; \
  StatusMsg: "Granting read access to sandboxed applications..."; \
  Flags: runhidden

[InstallDelete]
; The settings app used to be called frontend.exe: Tauri names the main
; binary after the crate unless `mainBinaryName` says otherwise, and it did
; not until #97.
;
; Tauri's own installer removes the old name when it changes — but only once,
; and only if the file is not in use. Upgrading with the settings app OPEN
; leaves a 10 MB orphan, because its running-instance check looks for the NEW
; name and so never stops the old process; and the removal is never retried,
; because by then the registry records the new name and the condition that
; triggers it can no longer be true. Verified on a test machine, both ways.
;
; So Setup deletes it here, unconditionally and before the copies, with the
; old name added to the stop list below so the file is not locked when this
; runs.
;
; Remove both once no supported upgrade path starts from a build older
; than #97.
Type: files; Name: "{app}\frontend.exe"

[UninstallDelete]
; launch.vbs is created at post-install by [Code], so Setup does not track
; it; delete it explicitly, otherwise it keeps {app} from being removed
Type: files; Name: "{app}\launch.vbs"
; ui.exe.WebView2 is the same story: builds before the %LOCALAPPDATA% move
; (issue #54) let WebView2 create its profile next to the exe, and a folder
; Setup never installed is a folder Setup never removes.
Type: filesandordirs; Name: "{app}\ui.exe.WebView2"
; An upgrade renames a TIP DLL it cannot delete out of the way rather than
; failing on it (MoveAsideInUseFile, #100), and sweeps the leftovers on the
; next upgrade. The last install never gets a next one, so they are removed
; here — and whatever is still loaded right now is deferred to the restart
; UninstallNeedRestart already asks for.
Type: files; Name: "{app}\*.dll.old-*"

[UninstallRun]
; stop the running IME processes first, or their exe/dll files stay locked
; and {app} can't be removed (UninstallNeedRestart hides this by deferring
; deletion to the reboot, but the unregistered DLL keeps loading until then).
; Azookey.exe is the settings app, which Setup installs and removes itself
; and which cannot delete its own running exe either.
; NOT runascurrentuser: that de-elevates the child, and launcher.exe runs as
; administrator — a de-elevated taskkill cannot touch it, and only an
; elevated schtasks may delete a machine-scope task.
Filename: "taskkill"; \
  RunOnceId: "KillAzookeyProcs"; \
  Parameters: "/F /IM launcher.exe /IM ui.exe /IM azookey-server.exe /IM plugin-host.exe /IM Azookey.exe"; \
  Flags: runhidden
Filename: "schtasks"; \
  RunOnceId: "DelAzookeyStartupTask"; \
  Parameters: "/Delete /TN ""Azookey Startup"" /F"; \
  Flags: runhidden

[Code]
function InitializeSetup: Boolean;
begin
  Dependency_AddVC2015To2022x64;
  Dependency_AddVC2015To2022x86;
  // Not optional, and easy to lose: the Tauri NSIS this setup used to chain
  // was the product's ONLY WebView2 bootstrap. ui.exe draws the candidate
  // window in WebView2 as much as the settings app does, so without the
  // runtime the IME comes up with no visible candidates and says nothing
  // about why. Same download and switches the chained installer used.
  Dependency_AddWebView2;

  Result := True;
end;

function UninstallNeedRestart(): Boolean;
begin
  Result := True;
end;

function CmdLineContains(Param: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
  begin
    if CompareText(ParamStr(I), Param) = 0 then
    begin
      Result := True;
      Exit;
    end;
  end;
end;
// Runs `schtasks` and reports whether it actually succeeded: ShellExec can
// fail to launch at all (returns False), and the process it launched can
// still exit non-zero. Both used to be discarded, which is how a task that
// was never created went unnoticed — see
// https://github.com/almandite1/azooKey-Windows/issues/83
function RunSchTasks(Args: String; var ErrorText: String): Boolean;
var
  ExitCode: Integer;
begin
  ErrorText := '';
  if not ShellExec('', 'schtasks', Args, '', SW_HIDE, ewWaitUntilTerminated, ExitCode) then
  begin
    ErrorText := 'schtasks を起動できませんでした (code ' + IntToStr(ExitCode) + ')';
    Result := False;
    Exit;
  end;
  if ExitCode <> 0 then
  begin
    ErrorText := 'schtasks が終了コード ' + IntToStr(ExitCode) + ' で失敗しました';
    Result := False;
    Exit;
  end;
  Result := True;
end;

procedure UpdateTaskXml();
var
  TaskXmlPath: string;
  TaskXmlContentAnsi: AnsiString;
  TaskXmlContent: String;
  ErrorText: String;
begin
  ExtractTemporaryFile('Azookey Startup.xml'); // ファイル展開
  TaskXmlPath := ExpandConstant('{tmp}\Azookey Startup.xml');

  LoadStringFromFile(TaskXmlPath, TaskXmlContentAnsi)

  TaskXmlContent := String(TaskXmlContentAnsi);

  StringChange(TaskXmlContent, 'PATH_TO_VBS', ExpandConstant('{app}\launch.vbs'));
  TaskXmlContentAnsi := AnsiString(TaskXmlContent);
  SaveStringToFile(TaskXmlPath, TaskXmlContentAnsi, False);

  // The install itself is fine either way — everything is already placed and
  // registered — so a failure here warns rather than aborts. But it must not
  // be silent: without the task the IME simply never starts at logon, and
  // nothing else would ever say why.
  if not RunSchTasks('/Create /F /TN "Azookey Startup" /XML "' + TaskXmlPath + '"', ErrorText) then
  begin
    MsgBox('自動起動タスクを作成できませんでした。' + #13#10 + ErrorText + #13#10#13#10 +
           'インストール自体は完了しています。ログオン時に azooKey が自動で起動しないため、' + #13#10 +
           '使用するたびに次を管理者として実行してください:' + #13#10 +
           ExpandConstant('{app}\launcher.exe'),
           mbError, MB_OK);
    Exit;
  end;

  // NOTE: never start a continuation line with `#`. The preprocessor runs
  // first and reads a leading `#` as a directive, so a wrapped string that
  // begins with `#13#10` fails to compile with "Unknown preprocessor
  // directive" — keep the character constants at the end of a line.
  if not RunSchTasks('/Run /TN "Azookey Startup"', ErrorText) then
    MsgBox('自動起動タスクは作成できましたが、今すぐ開始できませんでした。' + #13#10 +
           ErrorText + #13#10 + #13#10 +
           '次回のログオンからは自動で起動します。',
           mbInformation, MB_OK);
end;

procedure CreateVbsFile();
var
  VbsFile: string;
  VbsContent: AnsiString;
begin
  VbsFile := ExpandConstant('{app}\launch.vbs');
  VbsContent :=
    'Set objShell = CreateObject("WScript.Shell")' + #13#10 +
    // the path must be quoted inside the VBScript string (doubled quotes):
    // {app} contains a space, and an unquoted Run argument lets a planted
    // C:\Program.exe start instead — elevated, via the scheduled task
    'objShell.Run """' + ExpandConstant('{app}\launcher.exe') + '""", 0, False' + #13#10;

  if SaveStringToFile(VbsFile, VbsContent, False) then
  begin
    Log('VBS file created: ' + VbsFile);
  end
  else
  begin
    Log('Failed to create VBS file: ' + VbsFile);
  end;
end;

// Where the Tauri NSIS recorded itself. Setup no longer chains it, but every
// machine that installed a release before this one still has the key, and it
// is what puts a second "Azookey" in Installed apps (#104).
const
  LegacyNsisKey = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\Azookey';

// Removes what the chained Tauri NSIS left behind, so the upgrade ends with
// one Installed apps entry instead of two.
//
// Deleted explicitly rather than by running the old uninstall.exe /S. That
// uninstaller copies itself to %TEMP% (Au_.exe) and the original process
// exits at once, so ewWaitUntilTerminated returns long before the work is
// done — and the work is deleting {app}\Azookey.exe and a shortcut at the
// path Setup is about to write. Started from PrepareToInstall it would race
// the [Files] copies and could delete what this install just placed. What
// the old installer created is fully enumerated, so removing it by hand is
// both deterministic and testable.
//
// Guarded on the legacy key existing: on a first install there is nothing to
// clean, and nothing here should touch a same-named shortcut that is not ours.
procedure RemoveLegacyNsisSettingsApp();
var
  Location, AppDir, Desktop: String;
begin
  if not (RegKeyExists(HKLM, LegacyNsisKey) or RegKeyExists(HKCU, LegacyNsisKey)) then
    exit;

  Log('Found the legacy NSIS install of the settings app; removing it');

  // NSIS stores InstallLocation quoted (measured: "C:\Program Files\Azookey").
  // HKCU is the fallback for installs made before the perMachine switch,
  // which landed in the elevating administrator's hive.
  if not RegQueryStringValue(HKLM, LegacyNsisKey, 'InstallLocation', Location) then
    RegQueryStringValue(HKCU, LegacyNsisKey, 'InstallLocation', Location);
  Location := RemoveQuotes(Trim(Location));
  AppDir := ExpandConstant('{app}');
  if Location = '' then
    Location := AppDir;

  if DeleteFile(AddBackslash(Location) + 'uninstall.exe') then
    Log('Removed the legacy uninstaller from ' + Location);

  // In a default install both installers used the same directory, so the new
  // Azookey.exe simply lands on the old one and there is nothing to remove.
  // They differ only when the user pointed the outer installer somewhere
  // else: the chained NSIS ran silently and so always took ITS default.
  if CompareText(AddBackslash(Location), AddBackslash(AppDir)) <> 0 then
  begin
    if DeleteFile(AddBackslash(Location) + 'Azookey.exe') then
      Log('Removed the settings app from its old location ' + Location);
    // no-op unless the directory is now empty, which is the only case where
    // removing it is the right thing
    RemoveDir(Location);
  end;

  // the entry itself — the whole point
  if RegDeleteKeyIncludingSubkeys(HKLM, LegacyNsisKey) then
    Log('Removed the legacy uninstall entry from HKLM');
  if RegDeleteKeyIncludingSubkeys(HKCU, LegacyNsisKey) then
    Log('Removed the legacy uninstall entry from HKCU');

  // where the NSIS recorded its install directory; best effort, and the
  // parent only goes if nothing else lives under it
  RegDeleteKeyIncludingSubkeys(HKLM, 'SOFTWARE\azookey\Azookey');
  RegDeleteKeyIfEmpty(HKLM, 'SOFTWARE\azookey');
  RegDeleteKeyIncludingSubkeys(HKCU, 'SOFTWARE\azookey\Azookey');
  RegDeleteKeyIfEmpty(HKCU, 'SOFTWARE\azookey');

  // A silent NSIS created this for all users unconditionally — nobody chose
  // it, and Setup does not create one in its place.
  Desktop := ExpandConstant('{commondesktop}\Azookey.lnk');
  if DeleteFile(Desktop) then
    Log('Removed the desktop shortcut the silent chain created: ' + Desktop);
end;


// An upgrade installs over a running stack: launcher.exe, ui.exe and
// azookey-server.exe hold the installed executables open, so the [Files]
// copies land on in-use files and turn into a Restart Manager prompt, a
// forced app close, or an outright failure. The uninstaller already stops
// these processes; installation has to do the same first.
//
// Deliberately elevated — no runascurrentuser / ShellExecAsOriginalUser:
// launcher.exe runs as administrator, so a de-elevated taskkill cannot
// touch it.
//
// Note this does not unload azookey.dll from the text applications that
// have it loaded; those are the host's processes, not ours, and Inno's
// Restart Manager handling already covers that case.
//
// Line comments, not brace comments: a { } comment mentioning an Inno
// constant would be closed early by the constant's own closing brace.
// Counts our runtime processes, optionally terminating each, and reports
// whether WMI itself could be reached (Failed) — "could not look" is not the
// same answer as "none running".
//
// Why WMI rather than taskkill: taskkill can only match an image NAME, and
// ui.exe and launcher.exe are generic enough to belong to something else
// entirely, so /IM reached every one of them on the machine. A process is
// ours when it runs from the install directory; azookey-server.exe is
// matched by name alone because that name is already unambiguous, and so is
// Azookey.exe — which also stays name-matched because an upgrade from a
// build that installed it elsewhere still has to stop it.
//
// frontend.exe is the settings app's OLD name (see [InstallDelete] and #97).
// It is here so the file is not locked when Setup deletes it, and it is
// emphatically NOT in the name-only list — "frontend.exe" belongs to half the
// world. Only one under {app} is ours. Remove with the [InstallDelete] entry.
// WMI hands back NULL for fields we may not read (ExecutablePath on a
// process we cannot open), and Pascal Script has no VarToStr to absorb that.
function VariantText(const Value: Variant): String;
begin
  if VarIsNull(Value) or VarIsEmpty(Value) then
    Result := ''
  else
    Result := Value;
end;

function StackProcesses(const Dir: String; Kill: Boolean; var Failed: Boolean): Integer;
var
  Locator, Service, Items, Item: Variant;
  i: Integer;
  Prefix, Path, Name: String;
begin
  Result := 0;
  Failed := False;
  Prefix := Lowercase(AddBackslash(Dir));
  try
    Locator := CreateOleObject('WbemScripting.SWbemLocator');
    Service := Locator.ConnectServer('', 'root\CIMV2');
    Items := Service.ExecQuery('SELECT Name, ExecutablePath FROM Win32_Process' +
      ' WHERE Name = "launcher.exe" OR Name = "ui.exe"' +
      ' OR Name = "azookey-server.exe" OR Name = "plugin-host.exe"' +
      ' OR Name = "Azookey.exe" OR Name = "frontend.exe"');
    for i := 0 to Items.Count - 1 do
    begin
      Item := Items.ItemIndex(i);
      // plugin-host.exe is deliberately absent from the name-only list
      // below: it is as generic a name as ui.exe, so it is ours only when
      // it runs from the install directory.
      Name := Lowercase(VariantText(Item.Name));
      // ExecutablePath is NULL for processes we may not open; those are not
      // ours to kill anyway
      Path := Lowercase(VariantText(Item.ExecutablePath));
      if (Name = 'azookey-server.exe') or (Name = 'azookey.exe') or
         ((Path <> '') and (Pos(Prefix, Path) = 1)) then
      begin
        Result := Result + 1;
        if Kill then
        begin
          try
            Item.Terminate();
          except
            // already gone, or refused: the poll decides, not this call
          end;
        end;
      end;
    end;
  except
    Failed := True;
    Result := 0;
  end;
end;

procedure StopRunningStack();
var
  Dummy, Waited, Alive: Integer;
  Failed: Boolean;
begin
  // End the startup task first: it is what would put a fresh launcher back
  // between the kill and the copies.
  ShellExec('', 'schtasks', '/End /TN "Azookey Startup"', '', SW_HIDE, ewWaitUntilTerminated, Dummy);

  StackProcesses(ExpandConstant('{app}'), True, Failed);
  if Failed then
  begin
    // No WMI: fall back to the name-only kill. It is over-broad, but an
    // upgrade that cannot replace its locked files is the worse outcome.
    // Azookey.exe is the settings app, which [Files] is about to overwrite
    // and cannot while it runs.
    Log('WMI unavailable; falling back to a name-only taskkill');
    ShellExec('', 'taskkill', '/F /IM launcher.exe /IM ui.exe /IM azookey-server.exe /IM plugin-host.exe /IM Azookey.exe', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
    Sleep(1500);
    exit;
  end;

  // Termination is only REQUESTED above; the file handles close a moment
  // later. Poll for it instead of sleeping a fixed 1.5s, which proved
  // nothing on a slow machine and wasted the wait on a fast one.
  Waited := 0;
  repeat
    Alive := StackProcesses(ExpandConstant('{app}'), False, Failed);
    if (Alive = 0) or Failed then
      break;
    Sleep(250);
    Waited := Waited + 250;
  until Waited >= 15000;

  if Alive > 0 then
    Log('Timed out waiting for the running stack to exit; the file copies may hit locked files');
end;

// Moves a file that cannot be deleted out of the way, so the copy that
// follows lands on a free name. True means the path is clear afterwards.
//
// The TIP is loaded into every process that accepts text input, and none of
// them are ours: measured during an upgrade, {app}\azookey.dll was mapped
// into three explorer.exe, the Start menu's SearchHost.exe, and every
// application text had been typed into. Deleting a file whose image is
// mapped fails with ERROR_ACCESS_DENIED (5), which is the "DeleteFile error:
// code 5" dialog Setup showed on every upgrade (#100). Retry could never
// succeed, and Restart Manager does find those applications — measured, it
// names the shell and the store apps by title — but it cannot close the shell,
// and closing it would only make it reload the DLL when it comes back.
//
// Renaming works where deleting does not: NTFS allows a mapped image to be
// renamed within its directory. Processes holding the old image keep running
// from the renamed file until they exit, everything started afterwards loads
// the new one, and the registered path never changes, so the regserver flag
// on the [Files] entries still registers what it should.
//
// Measured on Windows 11 against a loaded DLL: DeleteFile -> 5, MoveFile ->
// success, and the renamed file still refuses to be deleted while it is
// loaded. That last part is why the leftovers are swept on the NEXT upgrade
// rather than this one.
function MoveAsideInUseFile(const Path: String): Boolean;
var
  I: Integer;
  MovedTo: String;
begin
  Result := True;
  if not FileExists(Path) then
    exit;
  // the ordinary case: nothing has it loaded, so leave no leftover behind
  if DeleteFile(Path) then
    exit;

  for I := 1 to 50 do
  begin
    MovedTo := Path + '.old-' + IntToStr(I);
    // a leftover from an earlier upgrade that is still loaded keeps its
    // name; take the next one
    if FileExists(MovedTo) then
      if not DeleteFile(MovedTo) then
        Continue;
    if RenameFile(Path, MovedTo) then
    begin
      Log('Moved the in-use ' + Path + ' aside as ' + MovedTo);
      exit;
    end;
  end;

  Log('Could not move ' + Path + ' aside; the copy will hit a locked file');
  Result := False;
end;

// Deletes what earlier upgrades moved aside, once nothing has it loaded any
// more. Best effort by design: a file still mapped into a long-lived process
// fails here and is retried by the next upgrade, and by [UninstallDelete] at
// the end of the product's life.
procedure SweepMovedAsideFiles(const Dir: String);
var
  Rec: TFindRec;
begin
  if not FindFirst(AddBackslash(Dir) + '*.dll.old-*', Rec) then
    exit;
  try
    repeat
      if DeleteFile(AddBackslash(Dir) + Rec.Name) then
        Log('Removed the leftover ' + Rec.Name);
    until not FindNext(Rec);
  finally
    FindClose(Rec);
  end;
end;

// Everything a host application can be holding — which is more than the TIP.
//
// msctf loads an in-proc TIP with the DLL's own directory on the search path,
// so the MSVC runtime the TIP imports is resolved out of {app} and mapped into
// the host as well. post_build documents the same lock for build/, where the
// DLL is registered from during development: "every process that loaded the
// IME holds build/vcruntime140.dll through the DLL search path". Measured in
// the VM with the shell, a store app and Notepad holding the TIP: moving only
// the two TIP DLLs aside got the copies past azookey.dll and then failed on
// vcruntime140.dll with the identical DeleteFile error 5.
//
// So the whole MSVC runtime group goes with them. Every name below is shipped
// unconditionally by [Files] — the two TIP entries and the build/* glob — so
// freeing one is safe: whatever is deleted or moved aside, the copies put
// back. That is the property to preserve when editing this list; a file Setup
// does not reinstall must not be added here.
//
// Not the Swift runtime or the engine's own DLLs: those are loaded by
// azookey-server.exe, which is ours and has just been stopped.
//
// azookey32.dll matters as much as azookey.dll: Setup is itself a 32-bit
// process, so with azooKey as the active IME the wizard can be holding the
// 32-bit TIP in its own process — "close the other applications first" was
// never a workaround the user could have found.
procedure MakeWayForTheTip();
var
  Dir: String;
begin
  Dir := ExpandConstant('{app}');
  // nothing to move on a first install
  if not DirExists(Dir) then
    exit;
  SweepMovedAsideFiles(Dir);
  Dir := AddBackslash(Dir);

  MoveAsideInUseFile(Dir + 'azookey.dll');
  MoveAsideInUseFile(Dir + 'azookey32.dll');

  MoveAsideInUseFile(Dir + 'vcruntime140.dll');
  MoveAsideInUseFile(Dir + 'vcruntime140_1.dll');
  MoveAsideInUseFile(Dir + 'vcruntime140_threads.dll');
  MoveAsideInUseFile(Dir + 'msvcp140.dll');
  MoveAsideInUseFile(Dir + 'msvcp140_1.dll');
  MoveAsideInUseFile(Dir + 'msvcp140_2.dll');
  MoveAsideInUseFile(Dir + 'msvcp140_atomic_wait.dll');
  MoveAsideInUseFile(Dir + 'msvcp140_codecvt_ids.dll');
  MoveAsideInUseFile(Dir + 'vccorlib140.dll');
  MoveAsideInUseFile(Dir + 'concrt140.dll');
end;

// Runs just before the file copies, and unlike a wizard-page hook it also
// runs for a silent install.
function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  StopRunningStack();
  // after the kill, which frees every file that is ours to free, and before
  // the copies, which is the whole point
  MakeWayForTheTip();
  // also before the copies: it deletes files at paths [Files] is about to
  // write, and Azookey.exe has just been stopped so nothing holds them
  RemoveLegacyNsisSettingsApp();
  Result := '';
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    CreateVbsFile();
    UpdateTaskXml();
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpFinished then
    WizardForm.RunList.Visible := False;
end;