; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "CodeDependencies.iss"

#define MyAppName "Azookey"
#define MyAppVersion "0.1.0-alpha.1"
; must match "version" in frontend/src-tauri/tauri.conf.json — the Tauri
; NSIS installer filename below is derived from it
#define TauriAppVersion "0.1.0"
#define TauriSetupExe "Azookey_" + TauriAppVersion + "_x64-setup.exe"
#define MyAppPublisher "fkunn1326"
#define MyAppURL "https://github.com/fkunn1326/azooKey-Windows/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{80B746D4-D74D-4345-8F81-47E06BCAB515}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Machine-wide install: this is an admin install (PrivilegesRequired=admin)
; that registers the IME machine-wide (HKCR/TSF, HKLM WER). {userappdata}
; would resolve to the ELEVATING admin's roaming profile — often a different
; account than the logged-in user — so the registered DLL paths could point
; into the wrong profile and other users would never find the files.
; {autopf} = Program Files (64-bit here), readable by every user. Mutable
; runtime data (settings.json, logs, dumps) lives in each user's
; %APPDATA%/%LOCALAPPDATA% via the app itself, not here.
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=../build
OutputBaseFilename=azookey-setup
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Files]
Source: "../build/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey.dll"; Flags: ignoreversion regserver 64bit
Source: "../build/x86/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey32.dll"; Flags: ignoreversion regserver 32bit
; exclude the installer's own output (OutputDir is also ../build): a stale
; azookey-setup.exe would otherwise be bundled into — or clash with — the new one
Source: "../build/*"; Excludes: "azookey-setup.exe"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "../target/release/bundle/nsis/{#TauriSetupExe}"; Flags: dontcopy noencryption
Source: "./Azookey Startup.xml"; Flags: dontcopy noencryption
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Windows Error Reporting LocalDumps: capture minidumps of native crashes
; (e.g. inside the Swift runtime or llama.cpp) for field diagnosis.
; DumpFolder is REG_EXPAND_SZ, so each user's dumps land in their own
; %LOCALAPPDATA%\Azookey\dumps. DumpType=1 = minidump, capped at 5 files.
; Only azookey-server.exe: LocalDumps keys match by exe NAME alone, so a
; generic name like ui.exe would also capture unrelated applications.
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: expandsz; ValueName: "DumpFolder"; ValueData: "%LOCALAPPDATA%\Azookey\dumps"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: dword; ValueName: "DumpType"; ValueData: "1"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\azookey-server.exe"; ValueType: dword; ValueName: "DumpCount"; ValueData: "5"

[Run]
Filename: "icacls"; \
  Parameters: "{app}\azookey.dll /grant ""*S-1-15-2-1:(RX)"""; \
  Description: "Grant Permission"; \
  Flags: runhidden postinstall runascurrentuser
Filename: "icacls"; \
  Parameters: "{app}\azookey32.dll /grant ""*S-1-15-2-1:(RX)"""; \
  Description: "Grant Permission"; \
  Flags: runhidden postinstall runascurrentuser

[UninstallDelete]
; launch.vbs is created at post-install by [Code], so Setup does not track
; it; delete it explicitly, otherwise it keeps {app} from being removed
Type: files; Name: "{app}\launch.vbs"

[UninstallRun]
Filename: "schtasks"; \
  RunOnceId: "DelAzookeyStartupTask"; \
  Parameters: "/Delete /TN ""Azookey Startup"" /F"; \
  Flags: runhidden runascurrentuser

[Code]
function InitializeSetup: Boolean;
begin
  ExtractTemporaryFile('{#TauriSetupExe}');
  Dependency_AddVC2015To2022x64;
  Dependency_AddVC2015To2022x86;
  Dependency_Add('{#TauriSetupExe}',
    '/q',
    'Azookey',
    '', '', True, False);

  Result := True;
end;

function UninstallNeedRestart(): Boolean;
begin
  Result := True;
end;

function CmdLineContains(Param: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
  begin
    if CompareText(ParamStr(I), Param) = 0 then
    begin
      Result := True;
      Exit;
    end;
  end;
end;
procedure UpdateTaskXml();
var
  TaskXmlPath: string;
  TaskXmlContentAnsi: AnsiString;
  TaskXmlContent: String;
  Dummy: Integer;
begin
  ExtractTemporaryFile('Azookey Startup.xml'); // ファイル展開
  TaskXmlPath := ExpandConstant('{tmp}\Azookey Startup.xml');

  LoadStringFromFile(TaskXmlPath, TaskXmlContentAnsi)

  TaskXmlContent := String(TaskXmlContentAnsi);

  StringChange(TaskXmlContent, 'PATH_TO_VBS', ExpandConstant('{app}\launch.vbs'));
  TaskXmlContentAnsi := AnsiString(TaskXmlContent);
  SaveStringToFile(TaskXmlPath, TaskXmlContentAnsi, False);

  ShellExec('', 'schtasks', '/Create /F /TN "Azookey Startup" /XML "' + TaskXmlPath + '"', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
  ShellExec('', 'schtasks', '/Run /TN "Azookey Startup"', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
end;

procedure CreateVbsFile();
var
  VbsFile: string;
  VbsContent: AnsiString;
begin
  VbsFile := ExpandConstant('{app}\launch.vbs');
  VbsContent :=
    'Set objShell = CreateObject("WScript.Shell")' + #13#10 +
    'objShell.Run "' + ExpandConstant('{app}\launcher.exe') + '", 0, False' + #13#10;

  if SaveStringToFile(VbsFile, VbsContent, False) then
  begin
    Log('VBS file created: ' + VbsFile);
  end
  else
  begin
    Log('Failed to create VBS file: ' + VbsFile);
  end;
end;

procedure UninstallAzookey();
var
  UninstallString: string;
  Dummy: Integer;
begin
  if RegQueryStringValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\Azookey', 'UninstallString', UninstallString) then
  begin
    if UninstallString <> '' then
    begin
      ShellExec('', UninstallString, '', '', SW_HIDE, ewWaitUntilTerminated, Dummy);
    end;
  end;
end;


procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    CreateVbsFile();
    UpdateTaskXml();
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpFinished then
    WizardForm.RunList.Visible := False;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    UninstallAzookey();
  end;
end;